name: Run Entando Bundle Pack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-entando-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare workspace directory
        run: |
          mkdir -p .entando/logs
          chmod -R 777 .entando

      - name: Login to Private Docker Registry
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin

      - name: Install OpenShift CLI
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
          OPENSHIFT_PASSWORD: ${{ secrets.OPENSHIFT_PASSWORD }}
        run: |
          curl -L -o oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xzf oc.tar.gz
          chmod +x oc
          sudo mv oc /usr/local/bin/
          oc login --server="$OPENSHIFT_SERVER" --username="$OPENSHIFT_USER" --password="$OPENSHIFT_PASSWORD" --insecure-skip-tls-verify=true
          oc project portali-entando
          bash <(curl -sL "https://get.entando.org/cli") --release="v7.3.0" --cli-version="v7.3.1"
          source "$HOME/.entando/activate" --force
          ent check-env develop --lenient
          ent bundle pack --org=mescalo
          ent bundle publish
          ent appname portali
          ent namespace portali-entando
          ent bundle generate-cr
          ent bundle install --conflict-strategy=OVERRIDE
